### ISSUE TITLE
Feature Request: Add a loading overlay

### ISSUE THREAD

**Issue by chmac** [cryptoboid/splitio#8]
Not sure why, but the data is taking >10s to load for me right now. Well, it hasn't loaded yet, so maybe it'll take longer! But it took me a while to realise that the title and heading both say "loading...". Would be great to add an overlay with a spinner so that I can't interact with the app until it's finished loading, and also so that I can't miss the fact that it's not yet loaded.

**Comment by cryptoboid** [comment]
From what I've tested, this mostly happens when there is a de-sync between peers. Usually gets fixed by having someone else with a copy open the group to refresh the data.

Also, it could happen when localStorage is full (AFAIK). In that last case, it can be fixed by using the IndexedDB plugin from Gun. Could you test if this version works OK for you? https://splitio-dev.vercel.app/ (just add the -dev to the links you use) The only difference is that it enables the IndexedDB plugin, but I haven't pushed it to main because I've had some crash reports

About the spinner: i've just implemented it, though I'm still interested in the previous test I've mentioned, to see if people are still getting crashes. thank you!

**Comment by chmac** [comment]
When I had that issue, I never saw the loading finish. I think I eventually cleared local data and refreshed the site and then it loaded again. So unfortunately I can't test the slow loading any more as I found a workaround.

Thanks for adding the spinner!
